package xraymux

import (
	"bytes"
	"context"
	"encoding/binary"
	"encoding/hex"
	"errors"
	"io"
	"net"
	"net/netip"
	"sync"
	"sync/atomic"
	"testing"
	"time"

	C "github.com/metacubex/mihomo/constant"
)

func testTarget() *C.Metadata {
	return &C.Metadata{NetWork: C.TCP, Host: "example.com", DstPort: 443}
}

func echoDialer(counter *int, mu *sync.Mutex) physicalDialer {
	return func(context.Context) (net.Conn, error) {
		client, server := net.Pipe()
		mu.Lock()
		*counter++
		mu.Unlock()
		go serveEchoMux(server)
		return client, nil
	}
}

func serveEchoMux(conn net.Conn) {
	defer conn.Close()
	for {
		id, status, option, err := readMetadata(conn)
		if err != nil {
			return
		}
		var payload []byte
		if option&optionData != 0 {
			var size [2]byte
			if _, err := io.ReadFull(conn, size[:]); err != nil {
				return
			}
			payload = make([]byte, binary.BigEndian.Uint16(size[:]))
			if _, err := io.ReadFull(conn, payload); err != nil {
				return
			}
		}
		if (status == statusNew || status == statusKeep) && len(payload) > 0 {
			meta, _ := encodeMetadata(id, statusKeep, optionData, nil, nil)
			var size [2]byte
			binary.BigEndian.PutUint16(size[:], uint16(len(payload)))
			buffers := net.Buffers{meta, size[:], payload}
			if _, err := buffers.WriteTo(conn); err != nil {
				return
			}
		}
	}
}

func TestEncodeMetadataMatchesMuxCoolLayout(t *testing.T) {
	frame, err := encodeMetadata(7, statusNew, 0, testTarget(), nil)
	if err != nil {
		t.Fatal(err)
	}
	want := []byte{
		0, 20, // metadata length
		0, 7, statusNew, 0, targetTCP,
		1, 187, // port 443, then Xray address
		2, 11, 'e', 'x', 'a', 'm', 'p', 'l', 'e', '.', 'c', 'o', 'm',
	}
	if !bytes.Equal(frame, want) {
		t.Fatalf("frame = %v, want %v", frame, want)
	}
}

func TestEncodeMetadataUDPIncludesGlobalID(t *testing.T) {
	target := &C.Metadata{NetWork: C.UDP, Host: "dns.google", DstPort: 53}
	gid := [8]byte{1, 2, 3, 4, 5, 6, 7, 8}
	frame, err := encodeMetadata(1, statusNew, optionData, target, &gid)
	if err != nil {
		t.Fatal(err)
	}
	if frame[6] != targetUDP {
		t.Fatalf("network = %d, want UDP", frame[6])
	}
	if !bytes.Equal(frame[len(frame)-8:], gid[:]) {
		t.Fatalf("global id missing: %v", frame)
	}
}

// These literals are derived independently from Xray-core common/mux and must
// not be generated by the production encoder: they guard against wire drift.
var xrayGoldenFrames = map[string]string{
	"domain-new-data":  "0014000101010101bb020b6578616d706c652e636f6d00026869",
	"domain-new-empty": "0014000101000101bb020b6578616d706c652e636f6d",
	"ipv4-new-empty":   "000c000201000100350101020304",
	"ipv6-new-empty":   "001800030100011f900300000000000000000000000000000001",
	"keep-data":        "00040001020100026f6b",
	"udp-new-data":     "001c00040101020035020b7564702e6578616d706c65000000000000000000027131",
	"xudp-new-data":    "001c00050101020035020b7564702e6578616d706c65010203040506070800027132",
	"udp-keep-data":    "001400040201020035020b7564702e6578616d706c6500027233",
	"end":              "000400010300",
}

func encodeTestFrame(id uint16, status, option byte, target *C.Metadata, globalID *[8]byte, payload []byte) ([]byte, error) {
	meta, err := encodeMetadata(id, status, option, target, globalID)
	if err != nil {
		return nil, err
	}
	if option&optionData == 0 {
		return meta, nil
	}
	var size [2]byte
	binary.BigEndian.PutUint16(size[:], uint16(len(payload)))
	return append(append(meta, size[:]...), payload...), nil
}

func TestEncodeMatchesXrayGoldenFrames(t *testing.T) {
	domainTCP := &C.Metadata{NetWork: C.TCP, Host: "example.com", DstPort: 443}
	ipv4TCP := &C.Metadata{NetWork: C.TCP, DstIP: netip.MustParseAddr("1.2.3.4"), DstPort: 53}
	ipv6TCP := &C.Metadata{NetWork: C.TCP, DstIP: netip.MustParseAddr("::1"), DstPort: 8080}
	udp := &C.Metadata{NetWork: C.UDP, Host: "udp.example", DstPort: 53}
	xudpID := [8]byte{1, 2, 3, 4, 5, 6, 7, 8}
	tests := []struct {
		name     string
		id       uint16
		status   byte
		option   byte
		target   *C.Metadata
		globalID *[8]byte
		payload  []byte
	}{
		{name: "domain-new-data", id: 1, status: statusNew, option: optionData, target: domainTCP, payload: []byte("hi")},
		{name: "domain-new-empty", id: 1, status: statusNew, target: domainTCP},
		{name: "ipv4-new-empty", id: 2, status: statusNew, target: ipv4TCP},
		{name: "ipv6-new-empty", id: 3, status: statusNew, target: ipv6TCP},
		{name: "keep-data", id: 1, status: statusKeep, option: optionData, payload: []byte("ok")},
		{name: "udp-new-data", id: 4, status: statusNew, option: optionData, target: udp, payload: []byte("q1")},
		{name: "xudp-new-data", id: 5, status: statusNew, option: optionData, target: udp, globalID: &xudpID, payload: []byte("q2")},
		{name: "udp-keep-data", id: 4, status: statusKeep, option: optionData, target: udp, payload: []byte("r3")},
		{name: "end", id: 1, status: statusEnd},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			got, err := encodeTestFrame(tt.id, tt.status, tt.option, tt.target, tt.globalID, tt.payload)
			if err != nil {
				t.Fatal(err)
			}
			want, err := hex.DecodeString(xrayGoldenFrames[tt.name])
			if err != nil {
				t.Fatal(err)
			}
			if !bytes.Equal(got, want) {
				t.Fatalf("frame mismatch\n got: %x\nwant: %x", got, want)
			}
		})
	}
}

func TestFirstPayloadIsCoalescedIntoNewFrame(t *testing.T) {
	observed := make(chan struct {
		status  byte
		option  byte
		payload string
	}, 1)
	pool := NewPool(Options{FirstPayloadTimeout: time.Second}, func(context.Context) (net.Conn, error) {
		client, server := net.Pipe()
		go func() {
			defer server.Close()
			_, status, option, err := readMetadata(server)
			if err != nil {
				return
			}
			var size [2]byte
			if _, err = io.ReadFull(server, size[:]); err != nil {
				return
			}
			payload := make([]byte, binary.BigEndian.Uint16(size[:]))
			if _, err = io.ReadFull(server, payload); err != nil {
				return
			}
			observed <- struct {
				status  byte
				option  byte
				payload string
			}{status, option, string(payload)}
		}()
		return client, nil
	}, func(context.Context) string { return "coalesce:443" })
	defer pool.Close()

	conn, err := pool.DialContext(context.Background(), testTarget())
	if err != nil {
		t.Fatal(err)
	}
	defer conn.Close()
	if _, err = conn.Write([]byte("hello")); err != nil {
		t.Fatal(err)
	}
	select {
	case got := <-observed:
		if got.status != statusNew || got.option != optionData || got.payload != "hello" {
			t.Fatalf("first frame = status %d option %d payload %q", got.status, got.option, got.payload)
		}
	case <-time.After(time.Second):
		t.Fatal("timed out waiting for first frame")
	}
}

func TestFirstPayloadTimeoutSupportsServerFirstProtocols(t *testing.T) {
	observed := make(chan [2]byte, 1)
	pool := NewPool(Options{FirstPayloadTimeout: 10 * time.Millisecond}, func(context.Context) (net.Conn, error) {
		client, server := net.Pipe()
		go func() {
			defer server.Close()
			_, status, option, err := readMetadata(server)
			if err == nil {
				observed <- [2]byte{status, option}
			}
		}()
		return client, nil
	}, func(context.Context) string { return "server-first:443" })
	defer pool.Close()

	conn, err := pool.DialContext(context.Background(), testTarget())
	if err != nil {
		t.Fatal(err)
	}
	defer conn.Close()
	select {
	case got := <-observed:
		if got != [2]byte{statusNew, 0} {
			t.Fatalf("timeout frame = %v", got)
		}
	case <-time.After(time.Second):
		t.Fatal("timed out waiting for empty New frame")
	}
}

func TestCloseBeforeFirstPayloadDoesNotSendLateNew(t *testing.T) {
	frames := make(chan byte, 2)
	pool := NewPool(Options{FirstPayloadTimeout: 20 * time.Millisecond}, func(context.Context) (net.Conn, error) {
		client, server := net.Pipe()
		go func() {
			defer server.Close()
			_ = server.SetReadDeadline(time.Now().Add(100 * time.Millisecond))
			for {
				_, status, _, err := readMetadata(server)
				if err != nil {
					return
				}
				frames <- status
			}
		}()
		return client, nil
	}, func(context.Context) string { return "close-before-new:443" })
	defer pool.Close()

	conn, err := pool.DialContext(context.Background(), testTarget())
	if err != nil {
		t.Fatal(err)
	}
	if err = conn.Close(); err != nil {
		t.Fatal(err)
	}
	select {
	case status := <-frames:
		if status != statusEnd {
			t.Fatalf("first frame after immediate close = %d, want End", status)
		}
	case <-time.After(time.Second):
		t.Fatal("timed out waiting for End frame")
	}
	time.Sleep(50 * time.Millisecond)
	select {
	case status := <-frames:
		t.Fatalf("unexpected late frame %d", status)
	default:
	}
}

func TestEndPayloadIsDrainedBeforeTerminalError(t *testing.T) {
	pool := NewPool(Options{FirstPayloadTimeout: -1}, func(context.Context) (net.Conn, error) {
		client, server := net.Pipe()
		go func() {
			defer server.Close()
			if _, _, _, err := readMetadata(server); err != nil {
				return
			}
			meta, _ := encodeMetadata(1, statusEnd, optionData|optionError, nil, nil)
			var size [2]byte
			binary.BigEndian.PutUint16(size[:], 4)
			buffers := net.Buffers{meta, size[:], []byte("tail")}
			_, _ = buffers.WriteTo(server)
		}()
		return client, nil
	}, func(context.Context) string { return "end-data:443" })
	defer pool.Close()

	conn, err := pool.DialContext(context.Background(), testTarget())
	if err != nil {
		t.Fatal(err)
	}
	defer conn.Close()
	buf := make([]byte, 4)
	if _, err = io.ReadFull(conn, buf); err != nil {
		t.Fatal(err)
	}
	if string(buf) != "tail" {
		t.Fatalf("payload = %q", buf)
	}
	_, err = conn.Read(make([]byte, 1))
	var protocolErr *ProtocolError
	if !errors.As(err, &protocolErr) {
		t.Fatalf("terminal error = %T %v, want *ProtocolError", err, err)
	}
}

func TestPoolFillsWorkerBeforeOpeningAnother(t *testing.T) {
	var mu sync.Mutex
	dials := 0
	// max-connections=0 → pack-first: fill soft concurrency before dialing another.
	pool := NewPool(Options{Concurrency: 2}, echoDialer(&dials, &mu), func(context.Context) string { return "test:443" })
	defer pool.Close()

	c1, err := pool.DialContext(context.Background(), testTarget())
	if err != nil {
		t.Fatal(err)
	}
	c2, err := pool.DialContext(context.Background(), testTarget())
	if err != nil {
		t.Fatal(err)
	}
	mu.Lock()
	if dials != 1 {
		t.Fatalf("two sessions opened %d physical connections", dials)
	}
	mu.Unlock()
	c3, err := pool.DialContext(context.Background(), testTarget())
	if err != nil {
		t.Fatal(err)
	}
	mu.Lock()
	if dials != 2 {
		t.Fatalf("third session opened %d physical connections", dials)
	}
	mu.Unlock()

	if _, err := c1.Write([]byte("hello")); err != nil {
		t.Fatal(err)
	}
	_ = c1.SetReadDeadline(time.Now().Add(time.Second))
	got := make([]byte, 5)
	if _, err := io.ReadFull(c1, got); err != nil {
		t.Fatal(err)
	}
	if string(got) != "hello" {
		t.Fatalf("echo = %q", got)
	}
	_ = c1.Close()
	_ = c2.Close()
	_ = c3.Close()
}

func TestPoolGrowsToMaxConnectionsBeforePacking(t *testing.T) {
	globalPermits = permitRegistry{counts: make(map[string]int)}
	var mu sync.Mutex
	dials := 0
	pool := NewPool(Options{Concurrency: 8, MaxConnections: 3}, echoDialer(&dials, &mu), func(context.Context) string {
		return "203.0.113.60:443"
	})
	defer pool.Close()

	var conns []net.Conn
	for i := 0; i < 3; i++ {
		c, err := pool.DialContext(context.Background(), testTarget())
		if err != nil {
			t.Fatalf("dial %d: %v", i, err)
		}
		conns = append(conns, c)
	}
	mu.Lock()
	if dials != 3 {
		t.Fatalf("soft-grow opened %d carriers, want 3", dials)
	}
	mu.Unlock()

	c4, err := pool.DialContext(context.Background(), testTarget())
	if err != nil {
		t.Fatal(err)
	}
	conns = append(conns, c4)
	mu.Lock()
	if dials != 3 {
		t.Fatalf("fourth session should pack, dials=%d", dials)
	}
	mu.Unlock()
	for _, c := range conns {
		_ = c.Close()
	}
}

func TestPoolDialRateLimitPacksInsteadOfDialing(t *testing.T) {
	globalPermits = permitRegistry{counts: make(map[string]int)}
	var mu sync.Mutex
	dials := 0
	pool := NewPool(Options{
		Concurrency:       8,
		MaxConnections:    3,
		MaxDialsPerMinute: 1,
	}, echoDialer(&dials, &mu), func(context.Context) string {
		return "203.0.113.61:443"
	})
	defer pool.Close()

	c1, err := pool.DialContext(context.Background(), testTarget())
	if err != nil {
		t.Fatal(err)
	}
	defer c1.Close()
	c2, err := pool.DialContext(context.Background(), testTarget())
	if err != nil {
		t.Fatal(err)
	}
	defer c2.Close()
	mu.Lock()
	defer mu.Unlock()
	if dials != 1 {
		t.Fatalf("rate limit should force pack, dials=%d want 1", dials)
	}
}

func TestPoolLeastLoadedSpreadsAcrossCarriers(t *testing.T) {
	globalPermits = permitRegistry{counts: make(map[string]int)}
	var mu sync.Mutex
	dials := 0
	pool := NewPool(Options{Concurrency: 8, MaxConnections: 2}, echoDialer(&dials, &mu), func(context.Context) string {
		return "203.0.113.62:443"
	})
	defer pool.Close()

	c1, _ := pool.DialContext(context.Background(), testTarget())
	c2, _ := pool.DialContext(context.Background(), testTarget())
	// Two carriers, one session each. Next two should land one on each (least-loaded).
	c3, err := pool.DialContext(context.Background(), testTarget())
	if err != nil {
		t.Fatal(err)
	}
	c4, err := pool.DialContext(context.Background(), testTarget())
	if err != nil {
		t.Fatal(err)
	}
	mu.Lock()
	if dials != 2 {
		t.Fatalf("dials=%d want 2", dials)
	}
	mu.Unlock()

	pool.mu.Lock()
	counts := []int{}
	for _, w := range pool.workers {
		w.mu.Lock()
		counts = append(counts, len(w.sessions))
		w.mu.Unlock()
	}
	pool.mu.Unlock()
	if len(counts) != 2 || counts[0] != 2 || counts[1] != 2 {
		t.Fatalf("session distribution %v, want [2 2]", counts)
	}
	_ = c1.Close()
	_ = c2.Close()
	_ = c3.Close()
	_ = c4.Close()
}

func TestPoolPacksOverflowInsteadOfDropping(t *testing.T) {
	globalPermits = permitRegistry{counts: make(map[string]int)}
	var mu sync.Mutex
	dials := 0
	// concurrency=2 => hard=8; maxConnections=1 forces packing beyond soft limit.
	pool := NewPool(Options{Concurrency: 2, MaxConnections: 1}, echoDialer(&dials, &mu), func(context.Context) string {
		return "203.0.113.1:443"
	})
	defer pool.Close()

	var conns []net.Conn
	for i := 0; i < 5; i++ {
		c, err := pool.DialContext(context.Background(), testTarget())
		if err != nil {
			t.Fatalf("dial %d: %v", i, err)
		}
		conns = append(conns, c)
	}
	mu.Lock()
	if dials != 1 {
		t.Fatalf("overflow packed onto %d workers, want 1", dials)
	}
	mu.Unlock()
	for _, c := range conns {
		_ = c.Close()
	}
}

func TestPoolWaitsWhenHardConcurrencyFull(t *testing.T) {
	globalPermits = permitRegistry{counts: make(map[string]int)}
	var mu sync.Mutex
	dials := 0
	// concurrency=1 => hard=4; fill all 4, then wait must respect context.
	pool := NewPool(Options{Concurrency: 1, MaxConnections: 1}, echoDialer(&dials, &mu), func(context.Context) string {
		return "203.0.113.9:443"
	})
	defer pool.Close()

	var conns []net.Conn
	for i := 0; i < 4; i++ {
		c, err := pool.DialContext(context.Background(), testTarget())
		if err != nil {
			t.Fatalf("dial %d: %v", i, err)
		}
		conns = append(conns, c)
	}
	ctx, cancel := context.WithTimeout(context.Background(), 50*time.Millisecond)
	defer cancel()
	if _, err := pool.DialContext(ctx, testTarget()); err == nil {
		t.Fatal("expected wait timeout when hard concurrency is full")
	}

	// Freeing a slot must unblock a waiter.
	_ = conns[0].Close()
	ctx2, cancel2 := context.WithTimeout(context.Background(), time.Second)
	defer cancel2()
	c, err := pool.DialContext(ctx2, testTarget())
	if err != nil {
		t.Fatalf("expected dial after free: %v", err)
	}
	_ = c.Close()
	for _, c := range conns[1:] {
		_ = c.Close()
	}
}

func TestPermitIsSharedAcrossPools(t *testing.T) {
	globalPermits = permitRegistry{counts: make(map[string]int)}
	var mu sync.Mutex
	dials := 0
	dial := echoDialer(&dials, &mu)
	key := func(context.Context) string { return netip.MustParseAddrPort("203.0.113.2:443").String() }
	// concurrency=1, hard=4 — fill hard on p1 so p2 cannot dial a new carrier and must wait/fail.
	p1 := NewPool(Options{Concurrency: 1, MaxConnections: 1}, dial, key)
	p2 := NewPool(Options{Concurrency: 1, MaxConnections: 1}, dial, key)
	defer p1.Close()
	defer p2.Close()
	var held []net.Conn
	for i := 0; i < 4; i++ {
		c, err := p1.DialContext(context.Background(), testTarget())
		if err != nil {
			t.Fatal(err)
		}
		held = append(held, c)
	}
	ctx, cancel := context.WithTimeout(context.Background(), 50*time.Millisecond)
	defer cancel()
	if _, err := p2.DialContext(ctx, testTarget()); err == nil {
		t.Fatal("second pool should not open beyond shared physical limit")
	}
	for _, c := range held {
		_ = c.Close()
	}
}

func TestWorkerRetiresAfterConfiguredUses(t *testing.T) {
	var mu sync.Mutex
	dials := 0
	const uses = 8
	pool := NewPool(Options{Concurrency: 1, MaxWorkerUses: uses}, echoDialer(&dials, &mu), func(context.Context) string { return "test:443" })
	defer pool.Close()
	for i := 0; i < uses; i++ {
		conn, err := pool.DialContext(context.Background(), testTarget())
		if err != nil {
			t.Fatalf("dial %d: %v", i, err)
		}
		_ = conn.Close()
	}
	conn, err := pool.DialContext(context.Background(), testTarget())
	if err != nil {
		t.Fatal(err)
	}
	defer conn.Close()
	mu.Lock()
	defer mu.Unlock()
	if dials != 2 {
		t.Fatalf("%d sessions opened %d workers, want 2", uses+1, dials)
	}
}

func TestConcurrentDialDoesNotSerializeOnExistingWorker(t *testing.T) {
	var mu sync.Mutex
	dials := 0
	var dialGate sync.WaitGroup
	dialGate.Add(1)
	slowDial := func(ctx context.Context) (net.Conn, error) {
		client, server := net.Pipe()
		mu.Lock()
		dials++
		n := dials
		mu.Unlock()
		if n == 1 {
			// First carrier is immediate.
			go serveEchoMux(server)
			return client, nil
		}
		// Subsequent dials block until released — must not block soft-alloc on worker 1.
		dialGate.Wait()
		go serveEchoMux(server)
		return client, nil
	}
	pool := NewPool(Options{Concurrency: 8}, slowDial, func(context.Context) string { return "test:443" })
	defer pool.Close()

	c1, err := pool.DialContext(context.Background(), testTarget())
	if err != nil {
		t.Fatal(err)
	}
	defer c1.Close()

	// Saturate soft concurrency so the next dial starts a new physical dial (blocked).
	var fillers []net.Conn
	for i := 0; i < 7; i++ {
		c, err := pool.DialContext(context.Background(), testTarget())
		if err != nil {
			t.Fatal(err)
		}
		fillers = append(fillers, c)
	}
	started := make(chan struct{})
	go func() {
		close(started)
		_, _ = pool.DialContext(context.Background(), testTarget())
	}()
	<-started
	time.Sleep(20 * time.Millisecond)

	// Free one soft slot; allocation onto the existing worker must succeed without
	// waiting for the in-flight physical dial.
	_ = fillers[0].Close()
	ctx, cancel := context.WithTimeout(context.Background(), 200*time.Millisecond)
	defer cancel()
	c, err := pool.DialContext(ctx, testTarget())
	if err != nil {
		t.Fatalf("soft alloc blocked by in-flight dial: %v", err)
	}
	_ = c.Close()
	dialGate.Done()
	for _, c := range fillers[1:] {
		_ = c.Close()
	}
}

func TestSessionPipeLimitMatchesXraySessionBuffer(t *testing.T) {
	// Guard against reintroducing the 64KiB mis-copy of xray's *worker* pipe
	// limit as the per-session download window (that capped speed at ~window/RTT).
	if sessionPipeLimit < 512*1024 {
		t.Fatalf("sessionPipeLimit=%d, want >= 512KiB (xray PerConnection)", sessionPipeLimit)
	}
	if carrierDownlinkLimit < 64*1024 {
		t.Fatalf("carrierDownlinkLimit=%d, want >= 64KiB (xray carrier pipe)", carrierDownlinkLimit)
	}
	if workerReadBuffer < 64*1024 {
		t.Fatalf("workerReadBuffer=%d, want >= 64KiB", workerReadBuffer)
	}
}

func TestPipeBackpressureDoesNotKillDownload(t *testing.T) {
	// Producer outruns consumer: the pipe must block (TCP backpressure), not
	// tear down the session. Killing on full was collapsing speedtest download.
	ln, err := net.Listen("tcp", "127.0.0.1:0")
	if err != nil {
		t.Fatal(err)
	}
	defer ln.Close()

	const total = 2 * 1024 * 1024 // well above the 512KiB session pipe
	payload := bytes.Repeat([]byte("D"), 4*1024)
	frames := total / len(payload)

	serverDone := make(chan error, 1)
	go func() {
		server, err := ln.Accept()
		if err != nil {
			serverDone <- err
			return
		}
		defer server.Close()
		if _, _, _, err := readMetadata(server); err != nil {
			serverDone <- err
			return
		}
		for i := 0; i < frames; i++ {
			meta, _ := encodeMetadata(1, statusKeep, optionData, nil, nil)
			var size [2]byte
			binary.BigEndian.PutUint16(size[:], uint16(len(payload)))
			buffers := net.Buffers{meta, size[:], payload}
			if _, err := buffers.WriteTo(server); err != nil {
				serverDone <- err
				return
			}
		}
		meta, _ := encodeMetadata(1, statusEnd, 0, nil, nil)
		if _, err := server.Write(meta); err != nil {
			serverDone <- err
			return
		}
		serverDone <- nil
	}()

	pool := NewPool(Options{Concurrency: 1}, func(context.Context) (net.Conn, error) {
		return net.Dial("tcp", ln.Addr().String())
	}, func(context.Context) string { return "test:443" })
	defer pool.Close()

	conn, err := pool.DialContext(context.Background(), testTarget())
	if err != nil {
		t.Fatal(err)
	}
	defer conn.Close()

	_ = conn.SetReadDeadline(time.Now().Add(5 * time.Second))
	got := 0
	buf := make([]byte, 8*1024)
	for got < total {
		n, err := conn.Read(buf)
		if n > 0 {
			got += n
		}
		if err == io.EOF {
			break
		}
		if err != nil {
			t.Fatalf("download aborted after %d/%d bytes: %v", got, total, err)
		}
	}
	if got != total {
		t.Fatalf("got %d bytes, want %d", got, total)
	}
	if err := <-serverDone; err != nil {
		t.Fatal(err)
	}
}

func TestReadMetadataRejectsMalformedLength(t *testing.T) {
	tests := map[string][]byte{
		"truncated length":             {0},
		"metadata shorter than header": {0, 3, 0, 0, 0},
		"oversized metadata":           {2, 1},
		"unknown status":               {0, 4, 0, 1, 9, 0},
		"unknown option":               {0, 4, 0, 1, statusKeep, 0x80},
		"new missing target":           {0, 4, 0, 1, statusNew, 0},
		"invalid network":              {0, 8, 0, 1, statusNew, 0, 9, 0, 80, 2},
		"end with target":              {0, 5, 0, 1, statusEnd, 0, 0},
	}
	for name, raw := range tests {
		t.Run(name, func(t *testing.T) {
			_, _, _, err := readMetadata(bytes.NewReader(raw))
			var protocolErr *ProtocolError
			if !errors.As(err, &protocolErr) {
				t.Fatalf("error = %T %v, want *ProtocolError", err, err)
			}
		})
	}
}

func TestDialDoesNotHoldLockAcrossPhysicalDial(t *testing.T) {
	var dials atomic.Int32
	started := make(chan struct{}, 2)
	release := make(chan struct{})
	dial := func(context.Context) (net.Conn, error) {
		dials.Add(1)
		started <- struct{}{}
		<-release
		client, server := net.Pipe()
		go serveEchoMux(server)
		return client, nil
	}
	pool := NewPool(Options{Concurrency: 1}, dial, func(context.Context) string { return "lock-test:443" })
	defer pool.Close()

	errCh := make(chan error, 2)
	for i := 0; i < 2; i++ {
		go func() {
			_, err := pool.DialContext(context.Background(), testTarget())
			errCh <- err
		}()
	}
	// While dial is blocked, Close must still return (pool lock not held across dial).
	<-started
	done := make(chan struct{})
	go func() {
		_ = pool.Close()
		close(done)
	}()
	select {
	case <-done:
	case <-time.After(200 * time.Millisecond):
		close(release)
		select {
		case <-done:
		case <-time.After(time.Second):
			t.Fatal("Close blocked while dial in progress")
		}
		return
	}
	close(release)
}
